#
# Scenario: Run the latest version of stock testing in Dev-1
#
apiVersion: scenario.test/v1beta1
kind: Scenario
metadata:
  name: stocktest
spec:
  environment: 
    name: development
    from: https://github.com/IBMStockTraderDemo/testscenarios
    version: HEAD
    file: environments/development.yaml
  
  virtualservices:
    - name: stock-quote-stub
      from: https://github.com/IBMStockTraderDemo/stockquotestub
      version: 7e2e3a03d44fdd8a90d13dfb983c2debf469f44f
      live-service: stock-quote
    - name: stock-quote-copy
      from: https://github.com/IBMStockTraderDemo/stockquotestub
      live-service: stock-quote
  
  tests:
    - name: portfoliotest
      from: https://github.com/IBMStockTraderDemo/portfoliotest
      targets:
      - name: trader
      - name: portfolio

      


