#
# Scenario: Run the latest version of stock testing in Dev-1
#
apiVersion: test.ibm.com/v1alpha1
kind: Testscenario
metadata:
  name: stockall-latest
spec:
  state: present
  scenario:
    virtualservices:
      - name: virtual-stock-quote
        description: A mock of the stock-quote service in the Stock Trader application (using Rational Integration Tester)
        type: rtvs
        from: https://github.com/IBMStockTraderDemo/stockquotestub
        #version: 7e2e3a03d44fdd8a90d13dfb983c2debf469f44f
        servicename: virtual-stock-quote-service
        containerports:
        - type: http
          port: 31002
        scale: 1
    
    tests:
      - name: portfoliotest
        type: rit
        from: https://github.com/IBMStockTraderDemo/portfoliotest
        scale: 1
        targets:
        - name: http://portfolio-service:9080
        - name: http://trader-service:9080
        - name: http://looper-service:9080
        
    configuration:
      virtualservices:
        - name: virtual-stock-quote
          map:
          - source: st-stock-quote-service
            target: virtual-stock-quote-service
      tests:
        - name: portfoliotest
          map:
          - source: portfolio-service
            target: st-portfolio-service
          - source: trader-service
            target: st-trader-service
          - source: looper-service
            target: st-looper-service
  