#
# Scenario: Run the latest version of stock testing in Dev-1
#
apiVersion: test.ibm.com/v1alpha1
kind: Testscenario
metadata:
  name: stockquote-stub
spec:
  state: present
  scenario:
    virtualservices:
      - name: virtual-stock-quote
        description: A mock of the stock-quote service in the Stock Trader application (using Rational Integration Tester)
        type: rtvs
        from: https://github.com/IBMStockTraderDemo/stockquotestub
        #version: 7e2e3a03d44fdd8a90d13dfb983c2debf469f44f
        servicename: virtual-stock-quote-service
        containerports:
        - type: http
          port: 31002
    
        
    configuration:
      services:
        map:
        - source: st29-2-stock-quote-service
          target: virtual-stock-quote-service
  