#
# Scenario: Run the latest version of stock testing in Dev-1
#
apiVersion: test.ibm.com/v1alpha1
kind: Testscenario
metadata:
  name: stockall-latest
spec:
  state: present
  scenario:    
    tests:
      - name: portfoliotest
        type: rit
        from: https://github.com/IBMStockTraderDemo/portfoliotest
        targets:
        - name: http://portfolio-service:9080
        - name: http://trader-service:9080
        - name: http://looper-service:9080
        
    configuration:
      tests:
        map:
        - source: portfolio-service
          target: st29-2-portfolio-service
        - source: trader-service
          target: st29-2-trader-service
        - source: looper-service
          target: st29-2-looper-service
  